# Generated by Django 5.2.11 on 2026-02-18 09:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(max_length=7, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'product colors',
            },
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['color', 'size']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='base_price',
            new_name='selling_price',
        ),
        migrations.AddField(
            model_name='product',
            name='damage_protection_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='One-time damage protection fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='late_return_penalty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Penalty per day for late return', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('rental', 'Rental')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='rental_price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_option',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('self_shipping', 'Self Shipping'), ('both', 'Both')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('gently_used', 'Gently Used'), ('worn_3_4', '3-4 Times Worn'), ('fair', 'Fair')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productcolor'),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('onesize', 'One Size')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('size',)},
            },
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productsize'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color', 'size')},
        ),
        migrations.CreateModel(
            name='RentalAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available_from', models.DateField(blank=True, null=True)),
                ('is_available_to', models.DateField(blank=True, null=True)),
                ('blocked_dates', models.JSONField(blank=True, default=list, help_text='List of blocked dates')),
                ('min_rental_days', models.PositiveIntegerField(default=1)),
                ('max_rental_days', models.PositiveIntegerField(default=365)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_availability', to='catalog.product')),
            ],
            options={
                'verbose_name_plural': 'rental availabilities',
            },
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock_quantity',
        ),
    ]
